version: "3.2"

services:
  mysqlserver:
    container_name: mysqlserver
    image: mysql/mysql-server:8.0.27
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: /entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password --wait_timeout=28800 --disable_log_bin

  glpi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - TIMEZONE=America/Sao_Paulo
    restart: always
    depends_on:
      - mysqlserver
    env_file:
      - .env
    entrypoint: []

